### PR TITLE
add MIT license

### PR DESCRIPTION
**Pull request by vaneyckt**
Heya,

Thanks for your work on this plugin. We really appreciate your efforts at Swrve, but we've been unable to track down which license your plugin false under. I would have preferred to simply open an issue about this, but your repo doesn't seem to accept issues :cry:, hence this pull request. I've added the MIT license in this PR, as it seems to be used quite frequently by Jenkins plugins, although you can of course choose whichever license you like.

### CODE REVIEW

**Comment by ikedam** [comment]
Jenkins plugins use JIRA for their issue tracker as you know: https://issues.jenkins-ci.org/browse/JENKINS-21270

**Comment by ikedam** [comment]
I can accept this request as all source files in groovy-postbuild are noted as MIT license in their heading comments.

**Comment by vaneyckt** [comment]
awesome stuff :rocket:

**Comment by ikedam** [comment]
Released 2.2.2 including this change.
It will be available in the update center in a day.

**Pull request merged**
