### PR TITLE
Fix broken links in help

### PR DESCRIPTION
**Pull request by orgads**
### Testing done

```[tasklist]
### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Thanks very much!

**Comment by orgads** [comment]
@MarkEWaite When will this be released?

**Comment by MarkEWaite** [comment]
Documentation fixes are usually not enough to trigger a new release.  It will be released when the next bug fix or new feature is added to the plugin. 

Is there something about this fix that needs it to release quickly?

**Comment by orgads** [comment]
No, that's fine. Just wondered.

**Pull request merged**
