### PR TITLE
JENKINS-54184  manager.removeSummaries() throws UnsupportedOperationException

### PR DESCRIPTION
**Pull request by kchuriumova**
__JIRA__: https://issues.jenkins-ci.org/browse/JENKINS-52043

Fixed the same way as https://issues.jenkins-ci.org/browse/JENKINS-52043
Tested on Jenkins, works just fine

### CODE REVIEW

**Comment by ikedam** [comment]
Thanks for the fix.
Looks good to me.

Could you add test codes like #37?

**Comment by kchuriumova** [comment]
thanks! sure

**Comment by kchuriumova** [comment]
Added tests here, is that OK?

**Comment by kchuriumova** [comment]
What need be to set to avoid permission issue for script?

**Comment by ikedam** [comment]
Please try `ScriptApproval#approveSignature()` like this: https://github.com/jenkinsci/groovy-label-assignment-plugin/blob/groovy-label-assignment-1.2.0/src/test/java/jp/ikedam/jenkins/plugins/groovy_label_assignment/GroovyLabelAssignmentPropertyJenkinsTest.java#L359

Or `ScriptApproval#preapprove()` may work: https://github.com/jenkinsci/groovy-postbuild-plugin/blob/groovy-postbuild-2.4.2/src/test/java/org/jvnet/hudson/plugins/groovypostbuild/GroovyPostbuildRecorderAnnotatedTest.java#L58

**Comment by kchuriumova** [comment]
Thanks, everything seems good. Ready for another look

**Comment by kchuriumova** [comment]
thanks, now should be fine, ready for another look

**Comment by ikedam** [comment]
Please turn off auto-formatter of IDE and leave white spaces of existing codes untouched.
I prefer to preserve existing codes and make it easier to track histories with `git blame`.

**Comment by zyzlik** [comment]
all done!

**Comment by kchuriumova** [comment]
all done!

**Comment by ikedam** [comment]
Thanks a lot!
I’ll make a new release groovy-postbuild-2.4.3 this weekend.

**Comment by ikedam** [comment]
link to JIRA: https://issues.jenkins-ci.org/browse/JENKINS-54184

**Comment by ikedam** [comment]
Released groovy-postbuild-2.4.3.
It will be available in the update center in a day.

**Pull request merged**
