### PR TITLE
Expose launcher to available variables.

### PR DESCRIPTION
**Pull request by KostyaSha**
Not tested yet

[Review on Reviewable](https://reviewable.io/reviews/jenkinsci/groovy-postbuild-plugin/20)

### CODE REVIEW

**Comment by KostyaSha** [comment]
@ikedam please review

**Comment by ikedam** [comment]
Sorry, I missed this request.

I don't think it's a good idea to expose `Launcher` even though it is protected with script-security.
* `Launcher` isn't easy to use for many users.
* Users aren't expected to launch external programs in post-build steps. They should do that in build steps. Post-build steps.

Please let me know for what purpose you want this feature.

**Comment by KostyaSha** [comment]
I thought it helper class. I need launcher for passing to various methods. Atm i use it for executing command on slave and i want avoid such tricks, because launcher is passed to perform and can be available in easiest way then:
```
 def node = manager.build.getBuiltOn()
 def launcher = node.createLauncher(listener)
```
I'm like user expect to have ability to wrote groovy code :) There is no post-build action that i need and writing another one plugin is not a good variant, so i just groovy simple things that i need.

**Comment by ikedam** [comment]
I know you want to run external programs on slave nodes.
For what purpose do you want to run external programs?

**Comment by KostyaSha** [comment]
Mvn, git etc, for debug or real purposes.
Btw i also searching 'tool' analog from https://github.com/jenkinsci/workflow-plugin/blob/master/TUTORIAL.md

**Comment by ikedam** [comment]
Hmm...I don't get why you have to do them in post-build phases.
I should encourage users to do those tasks in build step phases.

**Comment by KostyaSha** [comment]
@ikedam you can't mix steps from build-action with build-steps this is jenkins limitations that should die someday.

**Comment by ikedam** [comment]
You completely fail to make me feel this feature useful.
I think you want to use groovy-postbuild as a lightweight extension point or a lightweight workflow-plugin, but I don't plan so.

Please describe use cases where users expect this feature and how useful this is for many users.

**Comment by MarkEWaite** [comment]
Closing as inactive.

**Pull request closed without merging**
